### ISSUE TITLE
Call to undefined method introspectToken() 

### ISSUE THREAD

**Issue by nagman** [jumbojett/OpenID-Connect-PHP#184]
Hi,

I'm trying to validate an `id_token` on my backend (the frontend is already doing the Microsoft connect thing and sends back the `id_token` to the backend).

After looking at your docs, I can assume that `introspectToken` should do the job, am I right?

I mean, I already have the `id_token` and I've read that I should verify it on the backend side along with the secret key.

So I did this:
```
$authorizationEndpoint = 'https://login.microsoftonline.com/sdf5s46df5-sdf54s6-sdf5sd-sdf546s-sd5f4s6d5/oauth2/authorize';
$clientId = 'q6s5d4q6s5d-q6s5d4q6s5d-q5s4d';
$secretKey = '6qs5d4qs6d54s6q5d46qs';

$oidc = new OpenIDConnectClient($authorizationEndpoint, $clientId, $secretKey);
$data = $oidc->introspectToken($idToken);
```

And I get a Fatal error:
```
PHP Fatal error:  Uncaught Error: Call to undefined method Jumbojett\\OpenIDConnectClient::introspectToken()
```

**Comment by pendenga** [comment]
When you initialize the client, the first parameter $provider_url should be your 'well known configuration' instead of the authorize endpoint directly. The client will use the well-known configuration to discover the authorize endpoint as well as the introspection endpoint (if it is defined). In your example, your well-known configuration would be: 

https://login.microsoftonline.com/sdf5s46df5-sdf54s6-sdf5sd-sdf546s-sd5f4s6d5/v2.0/.well-known/openid-configuration

This client assumes it will find the introspection endpoint in the well-known configuration.

**Comment by nagman** [comment]
@pendenga Thanks for your help. Hope that it will help someone else because I've finally used another solution for my project.
