### ISSUE TITLE
Different file contents in repository and in  downloaded archive

### ISSUE THREAD

**Issue by MaximumRGB** [jumbojett/OpenID-Connect-PHP#216]
OpenIDConnectClient.php file in repository https://github.com/jumbojett/OpenID-Connect-PHP/tree/master/src and the same file in downloaded archive https://github.com/jumbojett/OpenID-Connect-PHP/archive/v0.9.0.zip are different. Why is it so?

**Comment by sbusch** [comment]
Because 0.9.0 is a release. It has been tagged on March 9th. See <https://github.com/jumbojett/OpenID-Connect-PHP/releases/tag/v0.9.0>

OTOH <https://github.com/jumbojett/OpenID-Connect-PHP/tree/master/src/OpenIDConnectClient.php> is on the `master` branch (see url) where all current development lands and where releases are regularly spun off.

So on master branch, there is the currently developed version and in the download, you get the version of the file at the time of tagging as 0.9.0.
