### ISSUE TITLE
Unable to dermine state error

### ISSUE THREAD

**Issue by pkowalezyk** [jumbojett/OpenID-Connect-PHP#266]
Hi, 

I'm using a front website which connect to an Ilias platform via OpenId Connect. 

However, I have an issue while doing the SSO connection. I get the following error : "Unable to determine state".
When I retry just after I don't have any error but after waiting a few minutes I have the error again.

Did someone have the same issue or have an explanation why I get this error? 

Thank you.

**Comment by safetimenow** [comment]
Yes I have the same issue since quite some time...

My code:
`$openIdConnection = new OpenIDConnectClient('XXX',
    'XXXX',
    'XXXX');

#$openIdConnection->setAllowImplicitFlow(true);
$openIdConnection->setResponseTypes(json_decode(getenv('OPENID_RESPONSE_TYPES')));
$openIdConnection->setRedirectURL('http://localhost:8888');
$openIdConnection->addScope('openid offline_access profile intranet');
$openIdConnection->addAuthParam(json_decode(getenv('OPENID_ADD_AUTH_PARAM')));

$openIdConnection->authenticate();

if (isset($_POST['id_token'])){
    $_SESSION['preferred_username'] = htmlspecialchars($openIdConnection->requestUserInfo('preferred_username'), ENT_QUOTES);
    echo "thats the username: ".$_SESSION['preferred_username'];
}`
The first time I run it I get the error: 

`:Uncaught Jumbojett\OpenIDConnectClientException: Unable to determine state in /srv/www/portal/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php:312
Stack trace:
#0 /srv/www/portal/public/index.php(37): Jumbojett\OpenIDConnectClient->authenticate()
#1 {main}
Line 312` 

When I refresh the site within a few seconds it works fine...

**Comment by DeepDiver1975** [comment]
> Unable to determine state

this means the session is not holding necessary/expected information.
this can happen with php7.4 due to the was owncloud is (by default) setting the same site cookie restrictions on the session cookie.

this same site cookies can be changed in config.php https://github.com/owncloud/core/blob/fa5d9130df999aa6ff8a11fc84e8d998fa42e5b8/config/config.sample.php#L265

please note that cookies need to be cleared from browsers and restarting apache is advised to reapply new cookies to the clients

**Comment by DeepDiver1975** [comment]
> Unable to determine state

this means the session is not holding necessary/expected information.

this can happen with php7.4 depending on the same site cookie restrictions on the session cookie.

At owncloud we advise to use None as same site cookie - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#values
https://github.com/owncloud/core/blob/fa5d9130df999aa6ff8a11fc84e8d998fa42e5b8/config/config.sample.php#L268

**Comment by DeepDiver1975** [comment]
> When I refresh the site within a few seconds it works fine...

if you refresh the session cookie is transmitted by the browser to the server because it is a same site request.
on the first call which is the redirect from the idp this is not the case.

**Comment by safetimenow** [comment]
So my default ini setting for samesite cookie was:
`session.cookie_samesite= ` empty... I tried all 3 possibilities ("None", "Strict", "Lax") and for all 3 I always get "Unable to determine State". Even after trying to refresh within a few seconds... So with the any variable set, it's not working at all anymore

**Comment by IljaN** [comment]
Try `SameSite=None; Secure`
