### ISSUE TITLE
Keycloak CODE_TO_TOKEN_ERROR doing a Browser reload

### ISSUE THREAD

**Issue by thorsten-l** [jumbojett/OpenID-Connect-PHP#366]
I just testet your sample code with Keycloak (21.0.2) as OIDC provider. Login and Logout works fine but a page reload get an error.

Keycloak LOG 
```
keycloak  | 2023-04-10 18:13:11,488 WARN  [org.keycloak.events] (executor-thread-0) 
type=CODE_TO_TOKEN_ERROR, realmId=eac9cf26-f820-4728-b127-3cb8a394622c, clientId=app3, userId=null, 
ipAddress=172.18.0.1, error=invalid_code, grant_type=authorization_code, 
code_id=5d2c454e-791c-4200-b5d1-231833c337ae, client_auth_method=client-secret
```

Page error
```
Fatal error: Uncaught Jumbojett\OpenIDConnectClientException: Code not valid in 
/var/www/html/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php:334 Stack trace: #0 
/var/www/html/protected.php(22): Jumbojett\OpenIDConnectClient->authenticate() #1 {main} thrown in 
/var/www/html/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php on line 334
```

**Comment by ricklambrechts** [comment]
Could you give some more context? Does the page that you reload, contain the code and state in the url?

The `->authorize()` function that runs when you are redirected back to the application on the redirect_url removes information from the session. So, you cannot reload that url, because that information is removed from session.

Normally after login and redirect back in the application, you have the access_token or user information available and you can do something with that. 

For example, set in the session that the user is signed in and redirect the user to the page that is available after signin.

**Comment by thorsten-l** [comment]
Thank you for your answer.
I'm sorry i am a Java or C person and i didn't understood the PHP concept. Now everything works fine.
