### ISSUE TITLE
undefined index $_SESSION['openid_connect_state']

### ISSUE THREAD

**Issue by Bubomir** [jumbojett/OpenID-Connect-PHP#93]
Hi I tried to use basic authentication from example but got error on line 1090

    Undefined index: openid_connect_state

my code is 

      $oidc = new OpenIDConnectClient($providerUrl, $clientId, $clientSecret);
    
      $oidc->authenticate();
      $oidc->addScope('email');

      $clientCredentialsToken = $oidc->requestClientCredentialsToken();

Thanks for any help

**Comment by jumbojett** [comment]
@Bubomir Thanks for the feedback. What version of PHP are you using? What provider are you trying to connect to?

I would make sure PHP SESSIONS are working properly. Set your debugger near the following and make sure the state is able to be set.

```
$state = $this->setState($this->generateRandString());
```

I hope this helps.

**Comment by Bubomir** [comment]
I'm using 

    PHP 7.0.18 with Symfony 3.3.0

my test provider is 

    https://mojeid.fred.nic.cz/

link to doc: 

    https://www.mojeid.cz/dokumentace/html/

the state is never set when i tried to verify it

I think is because before is condition on line 234 where is call this->getState() before the setState() call. 

    if ($_REQUEST['state'] != $this->getState()) {
        throw new OpenIDConnectClientException("Unable to determine state");
     }

or maybe is a some issue with Symfony ....

**Comment by torresmat** [comment]
The same thing happened to me yesterday. I solved by doing two things and now it's working... I really think its the second one that fix it:

1. I read somewhere that Symfony saves the session when the action in the controller ends.b This library is making use of the session inside and redirects by setting the "location" header not giving the change to the Symfony Framework to persist the session.

2. The action that I was using to redirect to my idp was being cached by the browser (it was a redirect response to the auth endpoint). The action named "/login" was never executed and when the user agent came back to the redirct uri there was no data in session (no state for example). I modified this code so the redirection can be made from the controller and set the cache-control and all-that-cache-header stuff so the redirect response won't get cached by the browser/varnish/whatever is in the middle. Maybe you can include those headers in the "redirect" method.

Bye!

**Comment by lingma1993** [comment]
@torresmat 
Hi, I meet the same problem that after redirection, Undefined index: openid_connect_state.
I try to modify the redirection's request and response. but the problem appeared random sometimes.
Could you please share the modification about the cache control ?
Thank you.

**Comment by ashishnarola** [comment]
@jumbojett can you please help us to fix this issue? I think issue is because of session only.
PFB:
https://prnt.sc/mtnlg4

My service provider is "Sparkplatform.com"

Looking forward for your kind help.

Thanks.

**Comment by torresmat** [comment]
Hi! Never noticed this comment here. I'll try to remember this when I get back home tomorrow. @ashishnarola are you using Symfony or just PHP? The same question goes for @lincentma . Sorry for the late reply!

> @torresmat
> Hi, I met the same problem that after redirection, Undefined index: openid_connect_state.
> I tried to modify the redirection's request and response. but the problem appeared random sometimes.
> Could you please share the modification about the cache control ?
> Thank you.

**Comment by PWalkow** [comment]
@torresmat Can you please show us how you have fixed this redirection from symfony controller?
as the library just change the location in the header we have the same problem here when trying to connect (Undefined index: openid_connect_state)

**Comment by torresmat** [comment]
Well, I haven't tried with the newest versions of this library. For what I can see there are some changes on how the library access the PHP session. 

Earlier in this post I stated that there might be 2 causes for this, and that I was more inclined to think that the second one was the problem:

1. The fact that symfony saves the session at the end of the controller action and that the OpenIdConnectClient class makes use of the $_SESSION array combined with a 302 redirect thus not allowing the controller action/function to end.
2. The redirect method inside the OpenIdConnectClient class that was making a redirect with no cache-control header. 

For what I can see the redirect method inside OpenIDConnectClient is making a 302 temporary redirect and, now, I don't think the browser is caching because only permanent redirects should be cached. The problem must be, then, the first reason I stated earlier.

When I solve this in the past I think I over-solved it. It was 3AM and I wanted this problem fixed so I attacked 1) and 2) in a number of different ways to solve the problem in 30 minutes and go to bed. 

Basically I modified the code so 

1. ...the library won't make use of the PHP session directly. Instead, I use the Symfony Session service inside the library. 
2. ...the library always returns an URL instead of making a redirect on its own (so symfony can do the redirect in the controller returning a Response object and persist the session correctly). 

I attached three files:

1. [OpenIDConnectService.php](https://github.com/jumbojett/OpenID-Connect-PHP/files/3136270/OpenIDConnectService.php.txt) OpenIDConnectService (wrapper of OpenIDConnectClient). You will see this class a little bit empty but that's because I removed handy symfony methods that only served me.
2. [OpenIDConnectClient.php.txt](https://github.com/jumbojett/OpenID-Connect-PHP/files/3136272/OpenIDConnectClient.php.txt) The modified OpenIDConnectClient class.
3. [OIDCController.php.txt](https://github.com/jumbojett/OpenID-Connect-PHP/files/3136277/OIDCController.php.txt) An example Controller using the OpenIDConnectService

**Comment by SpenzeR** [comment]
Got this error today:

`[2020-01-07 12:27:44] production.ERROR: Undefined index: openid_connect_state {"exception":"[object] (ErrorException(code: 0): Undefined index: openid_connect_state at /home/ubuntu/test/src/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php:1415)
[stacktrace]
#0 /home/ubuntu/test/src/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(1415): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/home/ubuntu/te...', 1415, Array)
#1 /home/ubuntu/test/src/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(284): Jumbojett\\OpenIDConnectClient->getState()
#2 /home/ubuntu/test/src/app/Http/Controllers/Auth/OidcController.php(80): Jumbojett\\OpenIDConnectClient->authenticate()`

Running php 7.3.11 w/Laravel 6.10 and OpenID-Connect-PHP v0.7

**Comment by bisaeed** [comment]
I used a cookie instead of a session and my problem was solved

`class myOpenId extends Jumbojett\OpenIDConnectClient {

    protected function getSessionKey($key) 
    {
        return $_COOKIE[$key];
    }

    protected function setSessionKey($key, $value) 
    {
        setcookie($key, $value, time() + 1728000, '/');
    }

    protected function unsetSessionKey($key) 
    {
        unset($_COOKIE[$key]);
    }
} `

**Comment by evifere** [comment]
I have the same problem here. Unable to determine state

```php
    private function authenticateByOpenIDConnect($code){
        $oidc = new OpenIDConnectClient(config('oidc.provider_uri'),
            config('oidc.client_id'),
            config('oidc.client_secret'));

        $oidc->setVerifyHost(false);
        $oidc->setVerifyPeer(false);
        $oidc->setHttpUpgradeInsecureRequests(false);

        $oidc->setRedirectURL(config('oidc.redirect_uri'));

        if($oidc->authenticate()){
            print_r($oidc->requestUserInfo());
        }

    }
```

The setState call is done after the getState

should i call another method before calling authenticate method ?

**Comment by lincentma** [comment]
This is an automatic reply, confirming that your email was received.I will reply as soon as possible.Thank you!
